import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import { PrimaryButton, SecondaryButton } from '../components/shared/button/button'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <PrimaryButton color="blue" size="large">Large Blue Primary</PrimaryButton>
        <PrimaryButton color="green" size="large">Large Green Primary</PrimaryButton>
        <PrimaryButton color="blue" size="small" disabled>Small Blue Primary Disabled</PrimaryButton>

        <SecondaryButton color="blue" size="large">Large Blue Secondary</SecondaryButton>
        <SecondaryButton color="blue" size="large" disabled>Large Blue Secondary Disabled</SecondaryButton>

        <Cards />
      </Main>
    </Container>
  )
}
